name: a1fbox-spamblock
version: "0.20220528"
summary: Block cold-calls in Germany
description: |
  Tools to block unwanted cold-calls in Germany via a fritzbox. 
  It's a snap of https://github.com/bufemc/a1fbox
base: core20
confinement: strict

parts:
  a1fbox:
    plugin: python
    requirements: [requirements.txt]
    override-build: |
      # XXX: submit upstream
      cat <<EOF>setup.py 
      import setuptools,glob
      setuptools.setup(
        name="a1fbox",
        version="0.0.1",
        url="https://github.com/bufemc/a1fbox",
        packages=setuptools.find_packages(),
        # HACK: make a1fbox look at some PATH defined location
        data_files=[("lib/python3.8/site-packages/data", glob.glob("data/*"))],
        python_requires='>=3.8',
      )
      EOF
      patch -p1 <<'EOF'
      diff --git a/a1fbox/callblocker.py b/a1fbox/callblocker.py
      index 0e96571..64e62ee 100644
      --- a/a1fbox/callblocker.py
      +++ b/a1fbox/callblocker.py
      @@ -225,7 +225,7 @@ class CallBlocker:

                   # ToDo: add that an event is only posted once if same full_number and e.g. not same minute
                   if TELEGRAM_BOT_URL:
      -                requests.get(TELEGRAM_BOT_URL + quote("CallBlocker: " + raw_line))
      +                requests.get(TELEGRAM_BOT_URL + quote("CallBlocker: " + str(parsed_line)))


       if __name__ == "__main__":
      EOF
      snapcraftctl build
    source: https://github.com/bufemc/a1fbox.git
  blocker:
    plugin: nil
    source: .
    override-build: |
      cp callblocker.py $SNAPCRAFT_PART_INSTALL/callblocker.py
      chmod +x $SNAPCRAFT_PART_INSTALL/callblocker.py
    
apps:
  blocker:
    command: ./callblocker.py
    daemon: simple
    plugs:
      - network
      - network-bind
    environment:
      # slightly ugly, config.py is imported so data dir needs to be first
      PYTHONPATH: $SNAP_DATA:$SNAP/lib/python3.8/site-packages:$SNAP/lib/python3.8/dist-packages:$PYTHONPATH
